version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:14-alpine  # Usa una versión específica y ligera para estabilidad y tamaño
    environment:
      POSTGRES_DB: databasename
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistencia de datos para no perder la base al reiniciar

  redis:
    container_name: redis_testqueues
    image: redis:7-alpine  # Versión específica y ligera
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data  # Persistencia opcional para redis, útil en desarrollo
volumes:
  pgdata:
  redisdata:
